### ISSUE TITLE
Get EEPROM1 Register (address = 05h) -  NIST traceability

### ISSUE THREAD

**Issue by rtek1000** [sparkfun/SparkFun_TMP117_Arduino_Library#12]
Hi,

I'm trying to use an Attiny85 as an interface for a Datalogger that operates with DS18B20 to be able to read the TMP117. For that, Attiny85 must operate with I2C and 1-wire (using this [lib](https://github.com/orgua/OneWireHub)), apparently it compiled without problems, using only 59% of Attiny85.

But I would like to use the TMP117 serial number for reference, when the Datalogger reads the DS18B20 emulated by Attiny85, it must return the value of the TMP117 serial.

I found this EEPROM1 (and EEPROM3) register (ds. pg. 30) that seems to be the TMP117 serial, but I didn't find a function in the library to access these EEPROM addresses, it might be interesting to add access to these other parts of the TMP117.

`7.6.7 EEPROM1 Register (address = 05h) [reset = XXXXh]`

`The EEPROM1 register is a 16-bit register that be used as a scratch pad`

`To support NIST traceability do not delete or reprogram the EEPROM[1] register.`

https://www.ti.com/lit/ds/symlink/tmp117.pdf

**Comment by nseidle** [comment]
Your PR was merged, thanks! If you end up writing helper functions to make EEPROM more easily accessible, please consider creating another PR, I'd welcome it.

**Comment by rtek1000** [comment]
@nseidle ,

I made an emulator for those who don't have the TMP117 boards at hand. If anyone needs a virtual TMP117 for preliminary testing of the examples, I think it might be helpful (works with ATmega328 based boards only):

https://github.com/rtek1000/TMP117-Emulator

**Comment by nseidle** [comment]
Neat! Thanks!
