### ISSUE TITLE
Ex1 fails to compile

### ISSUE THREAD

**Issue by nseidle** [sparkfun/SparkFun_TMP117_Arduino_Library#6]
When I pull the latest lib via lib manager Example 1 fails to compile. Perhaps the lib ver needs to be rolled? Please have a look.

**Comment by bboyho** [comment]
All examples compiles and works with the RedBoard Qwiic (ATmega328P) and the Artemis (Apollo3) after v1.2.0. I'm guessing this issue was fixed a while back.

Closing. ;)
